author: J. Morgan Lieberthal
github_url: https://github.com/baberthal/Yajl

theme: fullwidth
clean: true
min_acl: internal
docset_path: Yajl.docset

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-scheme, Yajl]
